#cloud-config
packages:
  - nfs-kernel-server
  - curl
  - wget
  - git
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - wget
runcmd:
  - mkdir -p /mnt/sharedfolder
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt update -y
  - apt install -y docker-ce docker-ce-cli containerd.io
  - usermod -aG docker ubuntu
  - while true; do { echo -e "HTTP/1.1 200 OK\r\n$(date)\r\n\r\n<h1>hello world</h1>" |  nc -vl -p 1234 -q1; break; } done &