#cloud-config 
chpasswd: #Change your local password here
    list: |
      ubuntu: NetApp!
    expire: false
users:
  - default #Define a default user
  - name: ubuntu
    gecos: ubuntu
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCe02Bi8JeOp1DVwlDeSm4+2joxAWBqfDdDzDCXAu4LIhx9WiFpe5n0t5hPwje+JEBN7UXvIiQHsdX3OrIVvgtOA7zRMiN9AVEB11pgNVXRPVRSZ2QYQk3m9ezhvYWaPX9/ZcZWL3T/xlDzR0tKtJlWK51ljoy6i+i+NZWhyUh+ZOpGQ1LAUliQeGg6QRl8jBfs6lGbhGPqm6JJXy8FOysiM08eQFaF3ood32GLCepiWNWuFyZqvoC7Qc7q+nYLeKQUxlPEDkimsGXkdvo4QnzNJ1nPsQ3zJP/gkF7dUgG1JVAd6RsniMLpiTaSNachRjPnf+i3zH9So3VaNoda+WRr jgriffith@cholula"
system_info: 
  default_user:
    name: default-user
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
#disable_root: false #Enable root acce
ssh_pwauth: yes #Use pwd to access (otherwise follow official doc to use ssh-keys)
random_seed:
    file: /dev/urandom
    command: ["pollinate", "-r", "-s", "https://entropy.ubuntu.com"]
    command_required: true
package_upgrade: true
packages:
  - python3-pip #Dependency package for cur
runcmd:
   - curl -sSL https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo/master/install.sh | sh - #Install cloud-init
power_state:
  timeout: 30
  mode: reboot
