#cloud-config 
packages:
  - nfs-kernel-server
  - curl
  - wget
  - git
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - software-properties-common
  - wget
runcmd:
    - mkdir -p /mnt/sharedfolder
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - apt update -y
    - apt install -y docker-ce docker-ce-cli containerd.io
    - usermod -aG docker ubuntu
    - wget https://get.helm.sh/helm-v3.2.3-linux-amd64.tar.gz
    - tar xzf helm-v3.2.3-linux-amd64.tar.gz
    - cp linux-amd64/helm /usr/local/bin/
    - helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
