name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Image
    needs: validate
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'master' }}
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: netapp/ez-rancher/terraform-rancher
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
          tags: "latest,${{ env.RELEASE_VERSION }}"
