name: Publish to Registry
on:
  release:
    types: [published]
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: git fetch --prune --unshallow
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(git describe --tags --abbrev=0)
      - name: Get commit revision
        id: get_commit
        run: echo ::set-env name=GIT_COMMIT::$(git rev-parse HEAD)
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: netapp/ez-rancher/terraform-rancher
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
          buildargs: GIT_COMMIT="${{ env.GIT_COMMIT }}"
          tags: "latest,${{ env.RELEASE_VERSION }}"
